version: "3.9"
services:
  redis:
    container_name: aircraft_tracker_redis
    image: "redis"
    ports:
      - 6379:6379
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure